//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class agencia
    {
        public int id { get; set; }
        public int destino_como_llegar_id { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public string imagen { get; set; }
    }
}
