//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class atractivo
    {
        public int id { get; set; }
        public string banner { get; set; }
        public string descripcion { get; set; }
        public string contenido { get; set; }
        public Nullable<int> destino_id { get; set; }
        public string resumen { get; set; }
        public Nullable<int> estado { get; set; }
        public string banner_t { get; set; }
        public string banner_m { get; set; }
        public string slug { get; set; }
        public string titulo { get; set; }
        public Nullable<int> destacado { get; set; }
    
        public virtual destino destino { get; set; }
    }
}
