//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class comunitario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comunitario()
        {
            this.comunitario_clima = new HashSet<comunitario_clima>();
            this.comunitario_hacer = new HashSet<comunitario_hacer>();
            this.comunitario_llegar = new HashSet<comunitario_llegar>();
            this.comunitario_precio = new HashSet<comunitario_precio>();
            this.comunitario_servicio = new HashSet<comunitario_servicio>();
            this.comunitario_tip = new HashSet<comunitario_tip>();
            this.categoria_comunitario = new HashSet<categoria_comunitario>();
            this.comunitario_imagen = new HashSet<comunitario_imagen>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string imagen { get; set; }
        public Nullable<int> provincia_id { get; set; }
        public string slug { get; set; }
        public string alt { get; set; }
        public string resumen { get; set; }
        public string descripcion { get; set; }
        public string thumb { get; set; }
        public Nullable<int> seo_id { get; set; }
        public string imagen_t { get; set; }
        public string imagen_m { get; set; }
        public Nullable<int> destacado { get; set; }
        public Nullable<int> activado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comunitario_clima> comunitario_clima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comunitario_hacer> comunitario_hacer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comunitario_llegar> comunitario_llegar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comunitario_precio> comunitario_precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comunitario_servicio> comunitario_servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comunitario_tip> comunitario_tip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categoria_comunitario> categoria_comunitario { get; set; }
        public virtual provincia provincia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comunitario_imagen> comunitario_imagen { get; set; }
    }
}
