//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class comunitario_llegar
    {
        public int comunitario_llegar_Id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tipotransporte_id { get; set; }
        public Nullable<int> comunitario_Id { get; set; }
    
        public virtual comunitario comunitario { get; set; }
        public virtual tipotransporte tipotransporte { get; set; }
    }
}
