//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class destino_como_llegar
    {
        public int destino_id { get; set; }
        public Nullable<int> como_llegar_id { get; set; }
        public string distancia { get; set; }
        public string tiempo_viaje { get; set; }
        public string waze { get; set; }
    }
}
