//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class icono
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string icono1 { get; set; }
        public string contenido { get; set; }
        public int mapa_id { get; set; }
    
        public virtual mapa mapa { get; set; }
    }
}
