//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticia
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public string resumen { get; set; }
        public string imagen { get; set; }
        public Nullable<int> likes { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int categoria_noticia_id { get; set; }
    
        public virtual categoria_noticia categoria_noticia { get; set; }
    }
}
