//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oferta()
        {
            this.opciones = new HashSet<opcione>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string subtitulo { get; set; }
        public string imagen { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> oferta1 { get; set; }
        public Nullable<decimal> precio_oferta { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_final { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<bool> estado_app { get; set; }
        public Nullable<bool> destacado { get; set; }
        public Nullable<int> tipo_oferta_id { get; set; }
        public int provincia_id { get; set; }
        public int categoria_id { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opcione> opciones { get; set; }
    }
}
