//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcione
    {
        public int id { get; set; }
        public int oferta_id { get; set; }
        public string incluye { get; set; }
        public string actividades { get; set; }
        public string condiciones { get; set; }
        public string nosotros { get; set; }
    
        public virtual oferta oferta { get; set; }
    }
}
