//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class place_activity
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string icono { get; set; }
        public Nullable<int> place_id { get; set; }
    
        public virtual place place { get; set; }
    }
}
