//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string resumen { get; set; }
        public string contenido { get; set; }
        public string imagen { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public Nullable<int> likes { get; set; }
        public Nullable<int> categoria_blog_id { get; set; }
        public Nullable<int> destacado { get; set; }
        public string slug { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> tipo_id { get; set; }
        public Nullable<int> provincia_id { get; set; }
        public Nullable<int> seo_id { get; set; }
        public string thumb { get; set; }
        public string imagen_t { get; set; }
        public string imagen_m { get; set; }
    }
}
