//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincia_comollegar
    {
        public int id { get; set; }
        public int como_llegar_id { get; set; }
        public string duracion { get; set; }
        public string distancia { get; set; }
        public string empresa { get; set; }
        public string waze { get; set; }
        public int provincia_id { get; set; }
        public Nullable<int> recomendar { get; set; }
    
        public virtual como_llegar como_llegar { get; set; }
        public virtual provincia provincia { get; set; }
    }
}
