//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ruta()
        {
            this.actividades = new HashSet<actividade>();
            this.mapas = new HashSet<mapa>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string tiempo_recorrido { get; set; }
        public string documento { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<bool> destacar { get; set; }
        public int rutascortas_id { get; set; }
        public int categoria_ruta_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividade> actividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mapa> mapas { get; set; }
        public virtual rutascorta rutascorta { get; set; }
    }
}
