//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class seo
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string og_title { get; set; }
        public string og_description { get; set; }
        public string og_image { get; set; }
        public string og_url { get; set; }
        public string twitter_card { get; set; }
        public string twitter_site { get; set; }
        public string twitter_creator { get; set; }
        public string twitter_domain { get; set; }
        public string twitter_title { get; set; }
        public string twitter_imagen { get; set; }
        public string twitter_account_id { get; set; }
        public string fb_app_id { get; set; }
        public string fb_admins { get; set; }
        public string scripts { get; set; }
        public string keywords { get; set; }
    }
}
