//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class slider_item
    {
        public int id { get; set; }
        public int slider_id { get; set; }
        public string imagen_xl { get; set; }
        public string imagen_lg { get; set; }
        public string imagen_md { get; set; }
        public string imagen_sm { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string alt { get; set; }
        public string url { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
