//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int idusuario { get; set; }
        public string nombre { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string email { get; set; }
        public Nullable<int> idrol { get; set; }
        public byte[] password_hash { get; set; }
        public byte[] password_salt { get; set; }
        public Nullable<bool> condicion { get; set; }
    
        public virtual role role { get; set; }
    }
}
